server:
  port: 80
spring:
  application:
    name: cloud-order-consumer
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # 采样率值介于0到1之间，1则表示全采集
      probability: 1
eureka:
  client:
    # 将自己注册进eureka中心
    register-with-eureka: true
    # 是否抓取注册信息，默认为true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
