server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh # payment_route  路由的ID,没有固定的规则但要求唯一
          uri: http://localhost:8001        #匹配后提供服务的路径地址
          predicates:
            - Path=/payment/get/**          #断言，路径相匹配进行路由

        - id: payment_routh2 # payment_route
          uri: http://localhost:8001
          predicates:
              - Path=/payment/lb/**
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    # 将自己注册进eureka中心
    register-with-eureka: true
    # 是否抓取注册信息，默认为true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
