server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh # payment_route  路由的ID,没有固定的规则但要求唯一
#          uri: http://localhost:8001        #匹配后提供服务的路径地址
          uri: lb://cloud-payment-service    #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**          #断言，路径相匹配进行路由

        - id: payment_routh2 # payment_route
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service    #匹配后提供服务的路由地址
          predicates:
              - Path=/payment/lb/**
              - After=2020-09-19T21:55:08.857+08:00[Asia/Shanghai]  # 这个时间之后才能访问，【时间获取方式测试类T2.java运行获取】
              - Cookie=username,zzyy  # 携带这个cookie才能访问
              - Hearder=X-Request-Id, \d+  # 请求头携带这个参数且正则匹配为整数才可访问
              - Method=GET           # GET请求方式才可访问
              - Query=username,\d+   # 参数username为整数才可访问
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    # 将自己注册进eureka中心
    register-with-eureka: true
    # 是否抓取注册信息，默认为true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
